name: detect-debug-code
on: pull_request
permissions:
    contents: read
    pull-requests: write
jobs:
  detect_debug_code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: checkout "${{ github.base_ref }}"
        with:
          fetch-depth: 1
          ref: ${{ github.base_ref }}
      - uses: actions/checkout@v4
        name: checkout "${{ github.head_ref }}"
        with:
          fetch-depth: 1
          ref: ${{ github.head_ref}}
      - uses: reviewdog/action-setup@v1
        name: setup reviewdog
        with:
          reviewdog_version: latest
      - name: detect_debug_code
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          files=(`git diff origin/${{ github.base_ref }} --name-only|tr '\n' ' ' `)
          .github/workflows/scripts/detect-debug-code/detect.sh "${files[@]}" | reviewdog -efm="%f:%l:%c: %m" -name="detect-debug-code" -reporter=github-pr-review -level=error
